{{if contains "4.5" .Values.daemonset.image.tag }} 
apiVersion: v1
data:
  log4j.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
    <log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">

        <appender name="ConsoleAppender" class="org.apache.log4j.ConsoleAppender">
            <layout class="org.apache.log4j.PatternLayout">
                <param name="ConversionPattern" value="%d{ABSOLUTE} %5p [%t] %c{1} - %m%n"/>
            </layout>
        </appender>

        <appender name="FileAppender" class="com.singularity.ee.agent.systemagent.SystemAgentLogAppender">
            <param name="File" value="logs/machine-agent.log"/>
            <param name="MaxFileSize" value="5000KB"/>
            <param name="MaxBackupIndex" value="5"/>
            <layout class="org.apache.log4j.PatternLayout">
                <param name="ConversionPattern" value="[%t] %d{DATE} %5p %c{1} - %m%n"/>
            </layout>
        </appender>

        <logger name="com.singularity" additivity="false">
            <level value="{{ .Values.agent.logLevel}}"/>{{if eq .Values.agent.stdoutLogging true}}
            <appender-ref ref="ConsoleAppender"/>{{ else }}
            <appender-ref ref="FileAppender"/>{{end}}
        </logger>

        <logger name="com.appdynamics" additivity="false">
            <level value="{{ .Values.agent.logLevel}}"/>{{if eq .Values.agent.stdoutLogging true}}
            <appender-ref ref="ConsoleAppender"/>{{ else }}
            <appender-ref ref="FileAppender"/>{{end}}
        </logger>

        <logger name="com.singularity.ee.agent.systemagent.task.sigar.SigarAppAgentMonitor" additivity="false">
            <level value="{{ .Values.agent.logLevel}}"/>{{if eq .Values.agent.stdoutLogging true}}
            <appender-ref ref="ConsoleAppender"/>{{ else }}
            <appender-ref ref="FileAppender"/>{{end}}
        </logger>

        <root>
            <priority value="error"/>
            <appender-ref ref="FileAppender"/>
        </root>

    </log4j:configuration>
kind: ConfigMap
metadata:
  name: ma-log-config
{{else}}
apiVersion: v1
data:
  log4j.xml: |-
    <?xml version="1.0" encoding="UTF-8" ?>
    <configuration status="Warn" monitorInterval="30">

        <Appenders>
            <Console name="ConsoleAppender" target="SYSTEM_OUT">
                <PatternLayout pattern="%d{ABSOLUTE} %5p [%t] %c{1} - %m%n"/>
            </Console>

            <RollingFile name="FileAppender" fileName="${log4j:configParentLocation}/../../logs/machine-agent.log"
                         filePattern="${log4j:configParentLocation}/../../logs/machine-agent.log.%i">
                <PatternLayout>
                    <Pattern>[%t] %d{DATE} %5p %c{1} - %m%n</Pattern>
                </PatternLayout>
                <Policies>
                    <SizeBasedTriggeringPolicy size="5000 KB"/>
                </Policies>
                <DefaultRolloverStrategy max="5"/>
            </RollingFile>
        </Appenders>

        <Loggers>
            <Logger name="com.singularity" level="{{ .Values.agent.logLevel}}" additivity="false">
            {{if eq .Values.agent.stdoutLogging true}}
                <AppenderRef ref="ConsoleAppender"/>
            {{else}}
                <AppenderRef ref="FileAppender"/>
            {{end}}
            </Logger>
            <Logger name="com.appdynamics" level="{{ .Values.agent.logLevel}}" additivity="false">
                {{if eq .Values.agent.stdoutLogging true}}
                <AppenderRef ref="ConsoleAppender"/>
                {{else}}
                <AppenderRef ref="FileAppender"/>
            {{end}}
            </Logger>
            <Logger name="com.singularity.ee.agent.systemagent.task.sigar.SigarAppAgentMonitor" level="{{ .Values.agent.logLevel}}" additivity="false">
                {{if eq .Values.agent.stdoutLogging true}}
                <AppenderRef ref="ConsoleAppender"/>
                {{else}}
                <AppenderRef ref="FileAppender"/>
            {{end}}
            </Logger>
            <Root level="error">
                <AppenderRef ref="ConsoleAppender"/>
            </Root>
        </Loggers>

    </configuration>
kind: ConfigMap
metadata:
  name: ma-log-config
{{end}}
