deployment:
  image:
    repository: docker.io/appdynamics/cluster-agent
    tag: latest
    pullPolicy: Always
  envValueFrom:
    APPDYNAMICS_AGENT_NODE_NAME:
      fieldRef:
        fieldPath: spec.nodeName
  envValueFromConfigMap: {}
  resources:
    limits:
      cpu: 200m
      memory: "300M"
    requests: 
      cpu: 100m
      memory: "100M"

controller:
  dns: ""
  port: ""
  ssl: ""
  accountName: ""
  accessKey: ""
  proxyUrl: ""
  proxyUser: ""
  

agent:
  appName: "K8s-Cluster-Agent"
  logLevel: INFO
  maxLogFileSize: 5
  maxLogBackups: 3
  writeToStdout: true
  containerRegInterval: 120
  eventUploadInterval: 10
  httpClientTimeout: 30
  metricsCollectionInterval: "30"
  clusterMetricsCollectionInterval: "60"
  metadataCollectionInterval: "60"
  containerRegBatchSize: "5"
  containerRegMaxParallelRequests: "1"
  podRegBatchSize: "6"
  metricUploadRetryCount: "2"
  metricUploadRetryInterval: "5"
  maxPodsToRegister: "750"
  containerFilter: "blacklisted-label: {appdynamics.exclude: true}"



  monitoredNamespaces: "default"



serviceAccount:
  name: appdynamics-cluster-agent

metrics-server:
  install: true
