{{ $mode := .Values.deploymentMode -}}
{{ $secret := .Values.controllerInfo.secret.create -}}
{{ if or (eq $mode "MASTER") (eq $mode "NAMESPACED") -}}
{{ if $secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-agent-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ with .Values.controllerInfo.secret -}}
  controller-key: {{ include "sensitiveData" (dict "data" .accessKey "message" "AppDynamics controller access key is required!") }}
  api-user: {{ cat (.username | trim | required "AppDynamics controller username is required!") "@" (.account | trim | required "AppDynamics controller account is required!") ":" (.password | trim | required "Appdynamics controller password is required!") | nospace | b64enc -}}
  {{- end -}}
{{ end -}}
{{ end -}}
