{{- if and (.Values.controller.apiUser) (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cluster-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cluster-agent.name" . }}
    helm.sh/chart: {{ include "cluster-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  api-user: {{ .Values.controller.apiUser | b64enc | quote }}
{{- if .Values.controller.controllerKey }}
  controller-key: {{ .Values.controller.controllerKey | b64enc | quote }}
{{- end }}
{{- if .Values.controller.eventKey }}
  event-key: {{ .Values.controller.eventKey | b64enc | quote }}
{{- end }}
{{- end }}
