apiVersion: v1
kind: Service
metadata:
  name: {{ include "machine-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "machine-agent.name" . }}
    helm.sh/chart: {{ include "machine-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.analytics.port }}
      targetPort: {{ .Values.analytics.port }}
      protocol: TCP
      name: analytics
  selector:
    app: {{ include "machine-agent.name" . }}
    release: {{ .Release.Name }}
